from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import List
import uuid
import os

def generate_docx(history: List[dict], title: str = "Firstchapter Export") -> str:
    doc = Document()

    # Title
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in heading.runs:
        run.font.color.rgb = RGBColor(0x1D, 0x9E, 0x75)

    doc.add_paragraph(f"Generated by Firstchapter.ai")
    doc.add_paragraph("")

    for i, item in enumerate(history, 1):
        # Question
        q_para = doc.add_paragraph()
        q_run = q_para.add_run(f"Q{i}: {item['question']}")
        q_run.bold = True
        q_run.font.size = Pt(12)
        q_run.font.color.rgb = RGBColor(0x1D, 0x9E, 0x75)

        # Answer
        doc.add_paragraph(item["answer"])

        # Sources
        sources = item.get("sources", [])
        if sources:
            src_para = doc.add_paragraph()
            src_run = src_para.add_run("Sources: ")
            src_run.bold = True
            src_run.font.size = Pt(10)
            for s in sources:
                src_para.add_run(
                    f"{s.get('book_title', '')} — {s.get('chapter', '')}  "
                ).font.size = Pt(10)

        doc.add_paragraph("")

    # Footer note
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(
        "Content sourced from licensed books via Firstchapter.ai"
    )
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0x88, 0x87, 0x80)

    out_path = f"/tmp/firstchapter_{uuid.uuid4().hex[:8]}.docx"
    doc.save(out_path)
    return out_path
