from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from typing import List
import uuid

GREEN  = RGBColor(0x1D, 0x9E, 0x75)
DARK   = RGBColor(0x2C, 0x2C, 0x2A)
GRAY   = RGBColor(0x88, 0x87, 0x80)
WHITE  = RGBColor(0xFF, 0xFF, 0xFF)

def add_text_box(slide, text, left, top, width, height, size=18, bold=False, color=DARK, align=PP_ALIGN.LEFT):
    box  = slide.shapes.add_textbox(left, top, width, height)
    tf   = box.text_frame
    tf.word_wrap = True
    para = tf.paragraphs[0]
    para.alignment = align
    run  = para.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    return box

def generate_pptx(history: List[dict], title: str = "Firstchapter Export") -> str:
    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]

    # ── Title slide ──────────────────────────────────────────────────────────
    slide = prs.slides.add_slide(blank_layout)
    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = RGBColor(0xF1, 0xEF, 0xE8)

    add_text_box(slide, title,
                 Inches(1), Inches(2.5), Inches(11), Inches(1.2),
                 size=36, bold=True, color=DARK, align=PP_ALIGN.CENTER)
    add_text_box(slide, "Generated by Firstchapter.ai",
                 Inches(1), Inches(3.9), Inches(11), Inches(0.5),
                 size=16, color=GREEN, align=PP_ALIGN.CENTER)

    # ── One slide per Q&A ────────────────────────────────────────────────────
    for i, item in enumerate(history, 1):
        slide = prs.slides.add_slide(blank_layout)

        # Green header bar
        bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(1.1))
        bar.fill.solid()
        bar.fill.fore_color.rgb = GREEN
        bar.line.fill.background()

        # Slide number
        add_text_box(slide, f"{i}", Inches(12.5), Inches(0.2), Inches(0.7), Inches(0.6),
                     size=14, bold=True, color=WHITE)

        # Question
        q_text = item["question"]
        if len(q_text) > 120:
            q_text = q_text[:120] + "..."
        add_text_box(slide, q_text,
                     Inches(0.4), Inches(0.15), Inches(11.5), Inches(0.75),
                     size=16, bold=True, color=WHITE)

        # Answer
        answer = item["answer"]
        if len(answer) > 700:
            answer = answer[:700] + "..."
        add_text_box(slide, answer,
                     Inches(0.5), Inches(1.3), Inches(12.3), Inches(4.8),
                     size=14, color=DARK)

        # Sources footer
        sources = item.get("sources", [])
        if sources:
            src_text = "Sources: " + " | ".join(
                f"{s.get('book_title','')} — {s.get('chapter','')}"
                for s in sources[:3]
            )
            add_text_box(slide, src_text,
                         Inches(0.5), Inches(6.7), Inches(12.3), Inches(0.5),
                         size=10, color=GRAY)

    out_path = f"/tmp/firstchapter_{uuid.uuid4().hex[:8]}.pptx"
    prs.save(out_path)
    return out_path
